name: "build"

on: [ push, pull_request, workflow_dispatch ]

jobs:
    build:
        name:    "PHP 8.1 / 9 "
        runs-on: ubuntu-latest

        steps:
            -   name: "Checkout"
                uses: actions/checkout@v2

            -   name: "Build environment"
                uses: shivammathur/setup-php@v2
                with:
                    php-version: "8.1"

            -   name: "Dependencies"
                run:  |
                      php --version
                      composer --version           
            -   name: "Tests"
                run:  ./run_tests.sh
            